"use client";
// src/pages/DisclaimerPage.tsx
import React from "react";

const DisclaimerPage: React.FC = () => {
  return (
    <div className="relative min-h-[75vh] max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-16 overflow-hidden">
      {/* Background radial glow */}
      <div className="absolute top-10 left-1/2 -translate-x-1/2 w-[600px] h-[600px] bg-purple-500/5 rounded-full blur-3xl pointer-events-none"></div>

      <div className="glass-card rounded-2xl shadow-2xl p-8 md:p-12 border border-gray-800/80 dark:border-gray-800/50 backdrop-blur-md relative z-10 animate-fade">
        <h1 className="text-3xl md:text-4xl font-extrabold text-white mb-2 bg-gradient-to-r from-purple-400 to-pink-500 bg-clip-text text-transparent">
          Disclaimer
        </h1>
        <p className="text-xs text-gray-500 mb-8">Last updated: June 15, 2026</p>

        <div className="space-y-8 text-gray-300 leading-relaxed text-sm md:text-base">
          <div>
            <h2
              id="no-advice"
              className="text-xl font-bold text-white mb-3"
            >
              1. Not Professional Advice
            </h2>
            <p className="mb-3">
              The images generated by AI Home Decorator ("Service") are for informational and inspirational purposes only. They do not constitute professional interior design, architectural, or engineering advice.
            </p>
            <p>
              You should not rely on these generated images as a substitute for consultation with qualified professionals. The Service does not guarantee compliance with United States building codes, safety regulations, zoning laws, or structural integrity. Always consult a licensed US contractor or architect before undertaking physical renovations. Any decisions made or actions taken based on the output of our Service are at your own sole risk.
            </p>
          </div>

          <div className="border-t border-gray-800/40"></div>

          <div>
            <h2 id="as-is" className="text-xl font-bold text-white mb-3">
              2. "As Is" Service
            </h2>
            <p>
              The Service is provided on an "AS IS" and "AS AVAILABLE" basis, without any warranties of any kind, either express or implied. We do not warrant that the generated designs will be accurate, complete, reliable, secure, or meet your specific requirements.
            </p>
          </div>

          <div className="border-t border-gray-800/40"></div>

          <div>
            <h2
              id="liability"
              className="text-xl font-bold text-white mb-3"
            >
              3. Limitation of Liability
            </h2>
            <p>
              In no event shall AI Home Decorator, its owners, or its affiliates be liable for any direct, indirect, incidental, special, or consequential damages (including, but not limited to, procurement of substitute goods or services; loss of use, data, or profits; or business interruption) however caused and on any theory of liability, whether in contract, strict liability, or tort (including negligence or otherwise) arising in any way out of the use of this Service, even if advised of the possibility of such damage.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DisclaimerPage;
