// src/pages/DisclaimerPage.tsx
import React from "react";

const DisclaimerPage: React.FC = () => {
  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8 text-gray-300">
      <div className="bg-gray-800/50 rounded-2xl shadow-xl p-6 md:p-8 border border-gray-700/50 prose prose-invert prose-lg max-w-none">
        <h1 className="text-3xl font-bold text-white">Disclaimer</h1>
        <p>Last updated: [03-11-2025]</p>

        <h2 id="no-advice">1. Not Professional Advice</h2>
        <p>
          The images generated by AI Home Decorator ("Service") are for
          informational and inspirational purposes only. They do not constitute
          professional interior design, architectural, or engineering advice.
        </p>
        <p>
          You should not rely on these generated images as a substitute for
          consultation with qualified professionals. Any decisions made or
          actions taken based on the output of our Service are at your own sole
          risk.
        </p>

        <h2 id="as-is">2. "As Is" Service</h2>
        <p>
          The Service is provided on an "AS IS" and "AS AVAILABLE" basis,
          without any warranties of any kind, either express or implied. We do
          not warrant that the generated designs will be accurate, complete,
          reliable, secure, or meet your specific requirements.
        </p>

        <h2 id="liability">3. Limitation of Liability</h2>
        <p>
          In no event shall AI Home Decorator, its owners, or its affiliates be
          liable for any direct, indirect, incidental, special, or consequential
          damages (including, but not limited to, procurement of substitute
          goods or services; loss of use, data, or profits; or business
          interruption) however caused and on any theory of liability, whether
          in contract, strict liability, or tort (including negligence or
          otherwise) arising in any way out of the use of this Service, even if
          advised of the possibility of such damage.
        </p>
      </div>
    </div>
  );
};

export default DisclaimerPage;
